### ISSUE TITLE
Cant compile app

### ISSUE THREAD

**Issue by connectnet** [tananaev/traccar-client-android#101]
By apk compiling with Eclipse 4.3 and SDK Im getting this error:
```
08-07 09:22:31.580: E/AndroidRuntime(1036): FATAL EXCEPTION: main
08-07 09:22:31.580: E/AndroidRuntime(1036): Process: org.traccar.client, PID: 1036
08-07 09:22:31.580: E/AndroidRuntime(1036): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{org.traccar.client/org.traccar.client.TraccarActivity}: java.lang.ClassNotFoundException: Didn't find class "org.traccar.client.TraccarActivity" on path: DexPathList[[zip file "/data/app/org.traccar.client-2.apk"],nativeLibraryDirectories=[/data/app-lib/org.traccar.client-2, /vendor/lib, /system/lib]]
08-07 09:22:31.580: E/AndroidRuntime(1036):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2121)
08-07 09:22:31.580: E/AndroidRuntime(1036):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
08-07 09:22:31.580: E/AndroidRuntime(1036):     at android.app.ActivityThread.access$800(ActivityThread.java:135)
08-07 09:22:31.580: E/AndroidRuntime(1036):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
08-07 09:22:31.580: E/AndroidRuntime(1036):     at android.os.Handler.dispatchMessage(Handler.java:102)
08-07 09:22:31.580: E/AndroidRuntime(1036):     at android.os.Looper.loop(Looper.java:136)
08-07 09:22:31.580: E/AndroidRuntime(1036):     at android.app.ActivityThread.main(ActivityThread.java:5017)
08-07 09:22:31.580: E/AndroidRuntime(1036):     at java.lang.reflect.Method.invokeNative(Native Method)
08-07 09:22:31.580: E/AndroidRuntime(1036):     at java.lang.reflect.Method.invoke(Method.java:515)
08-07 09:22:31.580: E/AndroidRuntime(1036):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
08-07 09:22:31.580: E/AndroidRuntime(1036):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
08-07 09:22:31.580: E/AndroidRuntime(1036):     at dalvik.system.NativeStart.main(Native Method)
08-07 09:22:31.580: E/AndroidRuntime(1036): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.traccar.client.TraccarActivity" on path: DexPathList[[zip file "/data/app/org.traccar.client-2.apk"],nativeLibraryDirectories=[/data/app-lib/org.traccar.client-2, /vendor/lib, /system/lib]]
08-07 09:22:31.580: E/AndroidRuntime(1036):     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
08-07 09:22:31.580: E/AndroidRuntime(1036):     at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
08-07 09:22:31.580: E/AndroidRuntime(1036):     at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
08-07 09:22:31.580: E/AndroidRuntime(1036):     at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
08-07 09:22:31.580: E/AndroidRuntime(1036):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2112)
## 08-07 09:22:31.580: E/AndroidRuntime(1036):     ... 11 more
```
Need some help. :-(

**Comment by ahmyt** [comment]
hello, 
i need help on compiling android client from android studio.
when i try compiling the hidden version, i keep getting the following error:
Error:Android Source Generator: [hidden] Package is not specified in AndroidManifest.xml

please help...

**Comment by tananaev** [comment]
@ahmyt, please provide details on how you imported the project and how you are trying to compile it.

**Comment by ahmyt** [comment]
Imported used from android studio:
1. Goto file > new > import project
2. From pop window, selected > traccar-client-android-master > create project from existing sources (gradle by default selected).
3. Clicked next > next > next > next > selected android api 19 > next > finish

Compiled:
1. Build > Generate signed apk > hidden > entered > entered key info >

Hope this helps....

----- Reply message -----

**Comment by ahmyt** [comment]
ok, the above error has been fixed now.

The current issue is that when i build the project with a debug build type, the app generated an apk without having any problem. However, when i used the release build type, i'm getting this error:

Error:(46, 1) Execution failed for task ':app:requestPasswords'.
> Cannot invoke method readPassword() on null object

**Comment by tananaev** [comment]
Please use command line to create a release build. You need to have a key store with your certificate to sign the binary.

**Comment by ahmyt** [comment]
ok all has been resolved with the client app.

Now im having problem with installing traccar on centos 64 bit VPS.
I logged in as root user through terminal and have installed java on the server and used the following command:

wget https://sourceforge.net/projects/traccar/files/traccar-linux-64-3.1.zip

unzip traccar-linux-64-3.1.zip

When i run ./traccar.run
it gives me error message:  (Verifying archive integrity... All good.
Uncompressing traccar  100%
./traccar.run: line 488: ./setup.sh: Permission denied)
i used chmod +x traccar.run  and still has same permission error

I really need help...

**Comment by tananaev** [comment]
You can try to extract files first and fix `setup.sh` file permissions. For available command line options run `./traccar.run --help`.

**Comment by ahmyt** [comment]
I have already extracted the traccar file and after extraction, there are only two files (traccar.run and readme.txt). I am facing the same issue permission denied.

Please provide me a detail solution...
regards,

**Comment by tananaev** [comment]
The `run` file is a self-extracting archive. You can try to extract it.

**Comment by ahmyt** [comment]
i have already extracted using ./traccar --target and gave an excute permission to setup.sh file.
When i run ./traccar.run, i am still getting the same issue:
Verifying archive integrity... All good.
Uncompressing traccar  100%
./traccar.run: line 488: ./setup.sh: Permission denied

Any solution...

**Comment by tananaev** [comment]
After you extract it, you need to run `setup.sh`. You can give me SSH access to check (email address is in profile).

**Comment by ahmyt** [comment]
I have sent you the ssh credentials.
any update please..

**Comment by tananaev** [comment]
Installed Traccar, but cannot start it because port 5075 is already in use by the system. You need to either stop process that uses that port or change/remove port in Traccar config.

**Comment by ahmyt** [comment]
Hello,

I have stoped the service running on port 5075 and traccar started successfully. However, when I try to browse myipaddress:8082 doesn't load traccar web page.

Any suggestions...?

----- Reply message -----

**Comment by tananaev** [comment]
I guess you need to check browser console. What does it say when you try to open it?

**Comment by ahmyt** [comment]
When I open browser it says connection timed out.
I used netstat -lt and I don't see the port 8082 in the list. If this is the problem, how do I open port 8082?

----- Reply message -----

**Comment by tananaev** [comment]
I can see it:
<pre>root@vps53982 [~]# netstat -ln | grep 8082
tcp        0      0 :::8082                     :::*                        LISTEN      </pre>

I guess you need to open the port on the firewall.

**Comment by ahmyt** [comment]
Cool finally worked on port 8082.
One final question, I changed the traccar.xml web port to 80 and restart the traccar service. But, when try to browse my ipaddress nothing display.

Any suggestions..

----- Reply message -----

**Comment by tananaev** [comment]
What is the error? Check browser console.

**Comment by mircea2003** [comment]
restart vps

**Comment by tiborko** [comment]
When compiling the release apk I am getting the error:  
Execution failed for task ':app:requestPasswords'.
> Cannot invoke method readPassword() on null object

I know, you suggested:   "use command line to create a release build"

I am completely new to Android Studio. Could you please point me to instructions/step by step on how to do that?  

BTW the install of the server went without a glitch, and was able to import your Android app using git. 

Thanks for all your hard work on this!!

**Comment by tananaev** [comment]
@tiborko, if you want to make a release build, you should do it from a command line. If you want to run the app from Android Studio, just use debug configuration.

**Comment by tiborko** [comment]
Anton,

I want to make a release build.  But I do not know what you mean when you
say: do it from a command line.

How do I build it from the command line?  Are there instructions, please.

Sorry for such a question.

Tibor

**Comment by tananaev** [comment]
You need to create a keystore first, update gradle script to use your keystore, and then assemble release build:
```
./gradlew assembleRegularRelease
```
or for hidden version:
```
./gradlew assembleHiddenRelease
```

**Comment by tiborko** [comment]
I set up a keystore with the appropriate .jks file as you suggested.
I found the gradle script.  What do I have to add/edit in the gradle script to make it use the .jks file in the keystore I set up?

**Comment by tananaev** [comment]
Modify this:

https://github.com/tananaev/traccar-client-android/blob/master/app/build.gradle#L16

**Comment by johansid** [comment]
Please open project structur.
Remove all keys first.
Clean project
Build
Generate apk with u key

-----Original Message-----

**Comment by tiborko** [comment]
I opened project structure, removed all keys, cleaned project, edited the build.gradle file to now contain references to my storeFile file, keyAlias, storePassword and keyPassword.

Now my question is (and thanks for both of you for helping): how do I run the ./gradlew assembleRegularRelease suggested by tananaev?  I understand it is supposed to be run from command line.  But where do I find the command line in Android Studio, I am running it on Windows 7?  Thank you again!

**Comment by tananaev** [comment]
There is no `gradlew` script for Windows in the project, so you would have to find another way.

**Comment by tiborko** [comment]
What platform are you developing on? I could set up an Ubuntu machine, is there an Android studio for that and the appropriate gradlew script in the project for that?

**Comment by tananaev** [comment]
I am using Ubuntu. Android Studio is available for Linux, but you don't even need it if you just want to compile release. Just get the code and run the command.

**Comment by tiborko** [comment]
Anton.  Thank you.  I think I will need Android Studio since I wanna make changes to your client.  If I go through the hassle of setting up an Ubuntu desktop and Install the Android Studio will I be able to compile there ?

**Comment by tananaev** [comment]
You will be definitely be able to compile from command line in Ubuntu. And develop your changes in Android Studio.
