### ISSUE TITLE
Estou com problemas com o APP (I'm in trouble app Traccar Client)

### ISSUE THREAD

**Issue by AleBarreto** [tananaev/traccar-client-android#122]
Erro ao importar o projeto do app para o android studio (error when I import the project to the studio android)

![erro](https://cloud.githubusercontent.com/assets/9629163/5622753/8a348444-952f-11e4-8a15-1b23f762f2ed.png)

**Comment by tananaev** [comment]
Do you import it or just open?

**Comment by AleBarreto** [comment]
I tried to import

**Comment by tananaev** [comment]
It is already Android Studio project, so try to just open it.

**Comment by AleBarreto** [comment]
I understood , it has a problem , my version of build gradle is updated and the package is out of date...

**Comment by tananaev** [comment]
Do you mean the project is using old one?

**Comment by AleBarreto** [comment]
I did so , I modified to buildToolsVersion " 21.1.2 " and buildTypes changed " minifyEnabled false" just like that, it worked in my android studio , 
Congratulations on your work (:

**Comment by tananaev** [comment]
I probably need to update Android Studio and fix the project.

**Comment by tananaev** [comment]
Fixed the project.
