### ISSUE TITLE
Crash on 'Mixed Provider' and 'Network Provider' 

### ISSUE THREAD

**Issue by flasheater** [tananaev/traccar-client-android#127]
When choosing the option 'Mixed Provider' or 'Network Provider' in 'Location provider' and starting the service, it immediately crashes.

The service tries to restart a couple of times, but crashes every time. Starting the client becomes impossible, because crashes occur instantly.

Tested on Nexus 5 with CM12.

Test on Nexus 10 with Android 5: No crashes occur. 

A notable difference between the devices is, that the Nexus 5 has no Google Play Services installed.

**Comment by tananaev** [comment]
Traccar Client does not use Google Play services, so it should work fine. Can you get logs from the device after crash?

**Comment by flasheater** [comment]
Yes I was about to, https://pastee.org/kfxf7. You are quick :).

**Comment by tananaev** [comment]
Looks like network provider doesn't exist:
<pre>-01 07:36:50.691 E/AndroidRuntime(6061): java.lang.RuntimeException: Unable to create service org.traccar.client.TraccarService: java.lang.IllegalArgumentException: provider doesn't exist: network
02-01 07:36:50.691 E/AndroidRuntime(6061): 	at org.traccar.client.PositionProvider.startUpdates(PositionProvider.java:68)
02-01 07:36:50.691 E/AndroidRuntime(6061): 	at org.traccar.client.TraccarService.onCreate(TraccarService.java:79)</pre>

**Comment by flasheater** [comment]
Do you think the network provider is only available with google services ? 

http://stackoverflow.com/questions/6775257/android-location-providers-gps-or-network-provider

This post suggests the fused provider, as a side note.

**Comment by flasheater** [comment]
Permissions seem right to me: 
http://imgur.com/u5thmwT
http://imgur.com/vfVaium

**Comment by tananaev** [comment]
Network provider usually works without Google Play services, but it still uses Google servers.
