### ISSUE TITLE
Saving data if no network connectivity

### ISSUE THREAD

**Issue by nichollascarter** [tananaev/traccar-client-android#130]
When there is no network connectivity i've got different situations - almost always data is not saved and i cant resolve this problem.
And second one when i turn on network location provider, my data come with a time by one hour ago.

Hope you understand me, hard to explain.

**Comment by tananaev** [comment]
The first problem happens because in many cases it's impossible to detect lost connection. It is a known issue and my plan is to change protocol to fix it.

As for the second one, please provide server logs.

**Comment by nichollascarter** [comment]
Понял. Я использовал исходники, изменил протокол для своего сервера, так как протокол Traccar и NMEA  не поддерживаются...

**Comment by nichollascarter** [comment]
private void reconnect() {
        handler.removeCallbacksAndMessages(null);
        connection.close();
        connection = new Connection(this);
        connection.connect(address, port);
    }

Подскажи, здесь убивается история?

**Comment by tananaev** [comment]
Вот тут удаляются сообщения из очереди:
https://github.com/tananaev/traccar-client-android/blob/master/traccar-client/src/main/java/org/traccar/client/ClientController.java#L133

**Comment by nichollascarter** [comment]
Вот, что происходит, если нет GPS сигнала, передается последнее время достоверных координат, а данные дублируются, это не считаю проблемой, за исключением времени...
#110415;060551;4454.9537;N;03404.9451;E;2;285;314;NA
#110415;060551;4454.9537;N;03404.9451;E;2;285;314;NA
#110415;060551;4454.9537;N;03404.9451;E;2;285;314;NA
#110415;060551;4454.9537;N;03404.9451;E;2;285;314;NA
#110415;060551;4454.9537;N;03404.9451;E;2;285;314;NA

А если выбрать сетевого провайдера, то данные идут со двигом на час назад
#110415;060458;4454.9298;N;03404.9645;E;0;0;0;NA

**Comment by tananaev** [comment]
В первом случаю время GPS передается, так что все корректно.

Что касается сетевого провайдера, думаю что какие-то проблемы с настройками часового пояса.

**Comment by nichollascarter** [comment]
А рассматривался вариант автоматического переключения на сетевого провайдера, если GPS сигнал отсутствует и обратно?

**Comment by tananaev** [comment]
Именно так и работает.

**Comment by nichollascarter** [comment]
Прошу прощения за назойливость, но зачем чистить историю при реконнекте?

**Comment by tananaev** [comment]
Никто не чистит историю при реконнекте.

**Comment by nichollascarter** [comment]
Возможно я ошибаюсь, но когда соединение пропадает и спустя некоторое время появляется, то срабатывает этот кусок сразу после установки соединения
https://github.com/tananaev/traccar-client-android/blob/master/traccar-client/src/main/java/org/traccar/client/ClientController.java#L133

**Comment by nichollascarter** [comment]
Здесь я не прав. Сообщения удаляются из очереди, а я имел ввиду удаление всей истории. Получается такой момент, что при переподключении сервис перезапускается и все сообщения удаляются, если конечно такое возможно...

**Comment by tananaev** [comment]
Я думаю что проблема в том что клиент не видит что соединение разорвано и продолжает слать сообщения в никуда.

**Comment by nichollascarter** [comment]
Тогда в таком случае нужно задуматься, чтобы клиент получал подтверждение пакета, прежде чем слать следующий.

**Comment by tananaev** [comment]
Подозреваю что Android просто убил приложение. Если это так, то думаю тут ничего уже не поможет.

**Comment by nichollascarter** [comment]
Не нашел причин почему сервис перезапускается. Проблему решил сохранением истории в файл с последующей выгрузкой при ре-коннекте.
