### ISSUE TITLE
GLONASS satellites are supported or not?

### ISSUE THREAD

**Issue by nichollascarter** [tananaev/traccar-client-android#132]
Please, can you explain,GLONASS satellites must be supported only by device or has some dependence from app?
Thanks.

**Comment by tananaev** [comment]
It depends on the device and protocol, but in most cases only device must support it and server doesn't know if it gets data from GPS or GLONASS.

**Comment by nichollascarter** [comment]
Thanks for answering. Now i've got some problem with data from gps locations provider: my phone shows that connection with gps successful but have no messages "updating location".
Network provider works for me.

**Comment by tananaev** [comment]
Are you trying it indoors? Note that GPS does not work inside buildings. Also check that GPS is enabled in the phone settings.

**Comment by nichollascarter** [comment]
Yes, sure. I do it on the streets and now it doesnt work... GPS is enabled.

**Comment by tananaev** [comment]
Do you see GPS icon on the status bar? If it's blinking it means phone can't get a GPS fix.

**Comment by nichollascarter** [comment]
I see GPS icon on the bar and it's not blinking.

**Comment by tananaev** [comment]
On some models it might not blink when it's looking for signal. Does it disappear after some time? Try to install some app that displays GPS status and see if it gets a fix.

**Comment by nichollascarter** [comment]
Earlier app worked perfectly, but now some problem. I did not do serious changes in the source code and i dont think this is a problem. I'll try your recommendations and answer for result later.

**Comment by nichollascarter** [comment]
Checked problem again, installed manually traccar client from apk file and gps data are missing. Install other app with gps support and it works, strange behavior...

**Comment by tananaev** [comment]
Are you sure other app is not using Network location?

**Comment by nichollascarter** [comment]
Of course, i use this "other" app when is no network connectivity

**Comment by tananaev** [comment]
Are you still using your modified version or official release? I guess the last option is to check Android log files and see if there is anything useful there.

**Comment by nichollascarter** [comment]
Can you help, where i must search android logs?

**Comment by tananaev** [comment]
If you are using one of the latest Android versions and your phone is not rooted, then the only option is to use <a href="http://developer.android.com/tools/help/logcat.html">adb logcat</a> to get logs.

**Comment by nichollascarter** [comment]
installed this app, does not see anything strange in logs...

**Comment by tananaev** [comment]
Which app did you install? Can I see the logs?

**Comment by nichollascarter** [comment]
Oh, i confused what i must to do. Ok, I'll connect my phone later, because i did not do it before, have been testing on virtual device.

**Comment by nichollascarter** [comment]
Can't check logs right now, but i tried determine problem and all i can see that gps is connected but
location = null, no messages like a "missing location provider"

**Comment by tananaev** [comment]
It's a standard Android API and I don't think it works differently for your device.

**Comment by nichollascarter** [comment]
Finally caught the problem.
https://github.com/tananaev/traccar-client-android/blob/master/traccar-client/src/main/java/org/traccar/client/PositionProvider.java#L101
Can you explain what is this condition of time? What is the purpose of this?

**Comment by tananaev** [comment]
The purpose is to avoid sending old location data. I guess system time on your phone is incorrect if that condition fails.

**Comment by nichollascarter** [comment]
Yes, you're right, wrong time settings. System time of my phone was more than gps time on some minutes. Thanks for support.
