### ISSUE TITLE
Use minimum distance option

### ISSUE THREAD

**Issue by nichollascarter** [tananaev/traccar-client-android#133]
I'm trying to change minimum distance option to value different from zero
https://github.com/tananaev/traccar-client-android/blob/master/traccar-client/src/main/java/org/traccar/client/PositionProvider.java#L69
but all that i've got it's updating location only by period when i'm not moving.
This variant must work or this is not enough?

**Comment by tananaev** [comment]
It won't work that easy because Traccar just requests last position periodically. You need to change position provide logic.

**Comment by nichollascarter** [comment]
Is it periodic updating?
https://github.com/tananaev/traccar-client-android/blob/master/traccar-client/src/main/java/org/traccar/client/PositionProvider.java#L81

**Comment by tananaev** [comment]
Correct, it is the method that does periodic updating.

**Comment by nichollascarter** [comment]
Please, can you answer, if i'll increase time of periodic updating, but request location period leave the same, can i use minimum distance option?

**Comment by tananaev** [comment]
I guess it would work, but it doesn't sound like a right way to do it.

**Comment by nichollascarter** [comment]
I checked it. Works only by time of periodic updating.

**Comment by nichollascarter** [comment]
Removed periodic updating, did logic like this and it works with minimum distance
  public void onLocationChanged(Location location) {
            handler.post(updateTask);
        }

**Comment by tananaev** [comment]
The problem with distance updates is that phone needs to always keep GPS on which will use battery very quickly.

**Comment by nichollascarter** [comment]
My purpose was don't send data when object still standing. This option needs for those who can charge phone all the time, usually when phone are using in the car.
