### ISSUE TITLE
Traccar andorid client mixed

### ISSUE THREAD

**Issue by shorty131** [tananaev/traccar-client-android#145]
Is it a bad thing to bring back mixed mode provider, becouse ,i cant always get gps signal on mobile,
why is that option deleted,and can i bring it back and recompile ,what would i lose with that ?

sorry for bad english ,i am just wondering what is pros and cons for mixed mode provider ?

**Comment by tananaev** [comment]
Android operating system has 2 location providers: GPS and Network. Mixed provider was implemented in the app using timers and for timers to work correctly application used to hold wake lock which has a huge negative impact on the battery usage.

It is possible to re-implement mixed provider using `AlarmManager` which should solve the power consumption problem, but it still won't be as efficient as using native Android providers.

**Comment by shorty131** [comment]
Ok, i know that mixed mode is implemented, i was thinking if i select provider as gps, just use gps ,but in case that gps not available than app to switch on network, but i never programmed an android app so i dont know is it posible ,i found on internet this peace of code public static boolean isLocationEnabled(Context context) {
    int locationMode = 0;
    String locationProviders;

    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT){
        try {
            locationMode = Settings.Secure.getInt(context.getContentResolver(), Settings.Secure.LOCATION_MODE);

        } catch (SettingNotFoundException e) {
            e.printStackTrace();
        }

        return locationMode != Settings.Secure.LOCATION_MODE_OFF;

    }else{
        locationProviders = Settings.Secure.getString(context.getContentResolver(), Settings.Secure.LOCATION_PROVIDERS_ALLOWED);
        return !TextUtils.isEmpty(locationProviders);
    }


}   is that code usable in your app ? Thanks.

**Comment by redge76** [comment]
WHy not use the fused location provider. Il depends on the Google Services but it seems like the recomended way to go. 
http://developer.android.com/training/location/receive-location-updates.html
(don't know the possible compatibility issues with the old devices ou devices without google services)

REdge

**Comment by tananaev** [comment]
@redge76, I have though about it and there a few reasons:

1. Devices without Google Play services won't be able to use the app
2. Old devices are not supported either
3. Linking against Google Play service library would significantly increase the size of the app

I also don't see the use case for mixed provider. Maybe someone can clarify it for me.

**Comment by tananaev** [comment]
@shorty131, it's a good idea and it should be possible to implement without too many changes. I will try to do it for the next release.

**Comment by shorty131** [comment]
Thanks a lot, waiting for the next release... :)

**Comment by shuricksumy** [comment]
Hi.
> I also don't see the use case for mixed provider. Maybe someone can clarify it for me.

Anton, to my mind, It very convenient do not care about setting of traccar-client-android and manually reconfigure and restart service every time when you change position provider on your phone.
    
It can happen when you use other navigation programs and these programs require gps provider and traccar-client-android use network provider. You turn on gps and of course forget to reconfigue and restart traccar-client-android. For this period traccar-client-android cannot update position with high definition.
    
Also can happen that your phone's battery is almost flat and you turn off gps module, but traccar-client-android was configured for gps using. And traccar-client-android will not update position.

**Comment by tananaev** [comment]
I have an idea on how to implement alternative to mixed provider. I will try to do it for the next major release.

**Comment by tananaev** [comment]
I have release Traccar Client for Android version 3.5 which includes a new implementation of mixed provider.
