### ISSUE TITLE
Same Packet Receiving

### ISSUE THREAD

**Issue by sunil553** [tananaev/traccar-client-android#149]
Hello

I am new to traccar-client-android . i have created a listener when i start traccar client service data is received at the server but the issue is same data packet is receiving every time.
I have checked in the code 
<pre>        @Override
        protected void onPostExecute(Boolean result) {
            if (result) {
                handler.onSuccess();
            } else {
                handler.onFailure();
            }
        }</pre>
here the result is false every time can i know the reason for that.

Thanks & Regards
Sunil B.

**Comment by tananaev** [comment]
I guess it doesn't receive a success response from the server.

Are you using Traccar server. If yes, try to look at the logs to see what server sends back.

**Comment by sunil553** [comment]
Hello Anton,


Thanks for quick response , Am using my windows server , What  response
that it should receive from the server.

**Comment by tananaev** [comment]
It should receive HTTP code 200 (OK).
