### ISSUE TITLE
Incompatibility between new Traccar client and old Traccar server.

### ISSUE THREAD

**Issue by hackerunet** [tananaev/traccar-client-android#153]
Anton, I would like to know if the last traccar client version is not compatible with old traccar server version 2.7 or 2.9.
Regards.

**Comment by tananaev** [comment]
It is compatible, but the protocol used by Traccar Client is different now. You have to use OsmAnd protocol (port 5055 by default).

**Comment by hackerunet** [comment]
thanks anton, I don't want to open a new case for a stupid question, so, can you please tell me how can I know which traccar server version do i have installed in my servers?
thanks

**Comment by tananaev** [comment]
You can look into the `tracker-server.log` file. When server starts it outputs there some system information including version number (unless you are using some ancient version that didn't have this functionality).

**Comment by hackerunet** [comment]
thank you very much!!, apparently I've been using traccar 2.3 and I think is time to move on, I tried to update to last version but seems to be not so stable as previous versions, what about upgrading to 2.12 version? is that version more stable? and is the configuration file the same as before version 3.0?

**Comment by tananaev** [comment]
What do you mean by not stable? You should be able to upgrade from 2.3 to 2.12 without much changes to the config.

For upgrade to 3.0 and 3.1 see following pages:

https://www.traccar.org/update-from-2-x-to-3-0/
https://www.traccar.org/update-from-3-0-to-3-1/

**Comment by hackerunet** [comment]
ok anton, thank you very much, well, I was testing last version and was not possible to make it run without crashing, It has the TCP stack problem and 5 minutes after starting the server, the TCP stack is full and it begins to fail, the failure is the same as always happened, it start to close opened connections and never receive again any other connections, so after 1 hour the traccar is still running but no connections are opened again.
This happens with large number of vehicles, let's say 3k.
I know is traccar version because in my server traccar 2.3 is running nicelly but I have to restart traccar service each hour so that way the TCP stack is cleared and new connections are created again.

**Comment by tananaev** [comment]
There were no changes to the connection management code. If you have `resetDelay` set up, old stale connections should be cleared out as before.

**Comment by hackerunet** [comment]
mmm, ok ok, let me upgrade to 2.12 first, test and also I need to create a new protocol based on gt06 device, my device send speed in hexadecimal and the gt06 protocol is processing speed from knots to kms.
So, let me download source code, create the protocol, test and after that I'll do my best to see how can I use last traccar version.
thanks  a lot anton.
