### ISSUE TITLE
App Shortcuts

### ISSUE THREAD

**Issue by abrileroux** [tananaev/traccar-client-android#161]
Hi there,

Thank you for all of your wonderful work!

I'm currently managing 6 trackers running on android phones with that need to be fairly autonomous. At the moment I'm using Real Time Tracker 2. I'm using Llama to tell the app to stop tracking when power is removed, and to start tracking when the device is charging.

All I need to do that is an android app shortcut "Start Tracking" and "Stop Tracking". It's working beautifully.

It would be wonderful if traccar could have shortcuts as well.

In this way it would be easy to use apps like Tasker, Llama or Automate to make it even more useful.

Real Time Tracker 2 has shortcuts for

"Start Tracking"
"Stop Tracking"
"Track once"

If you could point me in the right direction I can even try to help with the code, although I'm not the best coder out there :)

Kind regards,
Abri

**Comment by tananaev** [comment]
Thanks for the idea. People keep asking me to implement scheduling in the app, but I don't want to add that much extra functionality. Tasker and similar apps seem to be the perfect solution for the problem. Haven't though about it before.

I guess we just need to implement some custom actions for the app.
