### ISSUE TITLE
Gps103 ignoring "help me" Message without location

### ISSUE THREAD

**Issue by ivanfmartinez** [tananaev/traccar-client-android#164]
Hi,
testing an obd tracker inside my home, I have tried to use the sos button which send an "help me" message.
But the message is ignored by the gps103 decoder.

Here is one sample message (IMEI changed)
<pre>imei:359710099999999,help me,,,L,,,113b,,558f,,,,,0,0,,,;</pre>

I have tried to add this message in the Gps103ProtocolDecoderTest, and the error is "position is null"
Apparently the GPS signal is off where I'm testing, the tracker are sending the message and the decoder just ignoring because does not have a valid position.

Is possible to accept this kind of message and just use the last valid location for device and set an attribute indicating this ? Maybe setting "Valid" to false/no.

**Comment by tananaev** [comment]
First of all, why did you post this question in `traccar-client-android`? The question has nothing to do with Android app.

As for the question, those kind of messages will be supported starting from next release. The support is already implemented, so if you don't want to wait, you can compile a build from source code.

**Comment by ivanfmartinez** [comment]
Sorry, I created the issue in wrong place.
Creating in correct place.
