### ISSUE TITLE
Traccar Client not update when switch OFF GPS in Samsung Galaxy S4?

### ISSUE THREAD

**Issue by bernamaxim** [tananaev/traccar-client-android#169]
I have been set location provider to Mixed provider. When I switched ON my Location(GPS), it can update : "Location Updated", but when switched OFF, it cannot update to server and not show anything like "Location Updated" in STATUS log.

**Comment by bernamaxim** [comment]
![screenshot_2015-12-12-12-17-35](https://cloud.githubusercontent.com/assets/2969479/11760379/3151b1c8-a0cb-11e5-9148-cbe33bdb49d7.png)
If I switch GPS OFF, it cannot update location.

![screenshot_2015-12-12-12-19-11](https://cloud.githubusercontent.com/assets/2969479/11760381/32571c2a-a0cb-11e5-8003-0e238b125c93.png)
![screenshot_2015-12-12-12-19-19](https://cloud.githubusercontent.com/assets/2969479/11760380/31d51cd4-a0cb-11e5-89e5-43dad4cddddf.png)
If I switch GPS ON, it can update location, even if I set “Location Provider” at Traccar Client to Network provider.

**Comment by tananaev** [comment]
Mixed provider should switch to the network provider if GPS is not available. I need Android logs to check why it's not happening.

As for network provider, you don't need Wi-Fi for it if you have mobile data enabled.

**Comment by glbatistabh** [comment]
What was the solution?
I have the same problem on "Samsung Galaxy S5"

**Comment by tananaev** [comment]
You can access Android logs through ADB.
