### ISSUE TITLE
Old device id buffering

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar-client-android#171]
There have been many problems with the fact that device id is saved in the database. Two options to fix the issue:

1. Clear database when device id is changed
2. Do not save id in the database

**Comment by ivanfmartinez** [comment]
I think the option 2 is better.

**Comment by redge76** [comment]
Depends... If you change the ID, means that you assign the tracker to
someone/something else. If you don't save the ID, you will send data on the
wrong device ID..
No data may be better.
Maybe it would be better to enhance the client so taht it sends all the
data even if the server does not accept the device ID.
I already reported this issue some time ago:
https://github.com/tananaev/traccar-client-android/issues/151

Redge

**Comment by ivanfmartinez** [comment]
But if you are changing an android device to someone else, normally all data will be purged when you change the google account.

**Comment by redge76** [comment]
I changed the ID without changing the account..... I use a single google account for all my trackers.

**Comment by tananaev** [comment]
For now I decided to remove old data if device id has changed.
