### ISSUE TITLE
Auto update to from hidden version v.3.6 to v.3.8 breaks access to application

### ISSUE THREAD

**Issue by eallim** [tananaev/traccar-client-android#179]
I installed the traccar hidden release application (v3.6) from [https://www.traccar.org/client/](url)  to my old phone Android version 4.2.2

After installation I was able to set it up and confirm that it works on the server. Then I restarted my phone.

A while later I connected to wifi then Traccar auto-updated to version v3.8. Traccar is still hidden (no Traccar icon in the app list) and service is still running and updating to the server. In the app store the app registers as "installed" but only the "Uninstall" button shows up the "Open" button is missing. Also the 8722227 access code cannot open the app. In short auto-update breaks access to the Application.

Fixed it by Reinstalling the hidden version apk and disabling auto-updates.

p.s. Please advice people to disable auto-update for hidden release at the moment.

Cheers!

**Comment by tananaev** [comment]
This issue has been fixed since 3.6. The problem was that application ids were the same for regular and hidden versions. They are not any more.

**Comment by eallim** [comment]
I might have accidentally installed a older version then. Thanks for clarifying!
