### ISSUE TITLE
Data sync off 

### ISSUE THREAD

**Issue by johansid** [tananaev/traccar-client-android#183]
I have tried 2 cellphone device, and its normal.
After we add 4 cellphone, all service to port 5055 off and it will on again after reinstall.
It just happen for android client, on port 5002 data sync is normal

**Comment by tananaev** [comment]
Do you mean devices don't report data? If that's the case, please check status screen in the app.

**Comment by johansid** [comment]
yes...on server looks idle (offline).
I used hidden app, using lollipop.
If dial traccar,it will not open app screen.

Right now i reinstall all device with using location provider GPS, previous i use mixed.
Lets see what happen then..

**Comment by tananaev** [comment]
Hidden app should open. Do phones have sim cards? Check Android logs to see why it doesn't work.

**Comment by johansid** [comment]
yes..its use double sim cards.
here it is log:

--------- beginning of main
V/Monotype(18783): SetAppTypeFace- try to flip, app = org.jtb.alogcat
V/Monotype(18783): Typeface getFontPathFlipFont - systemFont = default#default
V/Monotype(18783): SetAppTypeFace- try to flip, app = org.jtb.alogcat
V/Monotype(18783): Typeface getFontPathFlipFont - systemFont = default#default
W/InputEventReceiver(18783): Attempted to finish an input event but the input event receiver has already been disposed.
V/Monotype(19079): SetAppTypeFace- try to flip, app = org.jtb.alogcat
V/Monotype(19079): Typeface getFontPathFlipFont - systemFont = default#default
V/Monotype(19079): SetAppTypeFace- try to flip, app = org.jtb.alogcat
V/Monotype(19079): Typeface getFontPathFlipFont - systemFont = default#default
D/WebViewFactory(19079): primaryArchIs64bit = false
I/WebViewFactory(19079): Loading com.google.android.webview version 48.0.2564.106 (code 256410610)
I/cr_LibraryLoader(19079): Time to load native libraries: 2 ms (timestamps 7700-7702)
I/cr_LibraryLoader(19079): Expected native library version number "48.0.2564.106", actual native library version number "48.0.2564.106"
V/WebViewChromiumFactoryProvider(19079): Binding Chromium to main looper Looper (main, tid 1) {34a9e7b2}
I/cr_LibraryLoader(19079): Expected native library version number "48.0.2564.106", actual native library version number "48.0.2564.106"
I/chromium(19079): [INFO:library_loader_hooks.cc(130)] Chromium logging enabled: level = 0, default verbosity = 0
I/cr_BrowserStartup(19079): Initializing chromium process, singleProcess=true
W/cr_media(19079): Requires BLUETOOTH permission

**Comment by tananaev** [comment]
I don't think it's the correct log. It's almost empty and doesn't have any info about Traccar Client.

**Comment by johansid** [comment]
i used alogcat app playstore, do you have any suggestion app?

**Comment by tananaev** [comment]
It works only for old versions of Android or rooted devices. The only way to get logs on newer version as far as I know is ADB tool.

**Comment by johansid** [comment]
ok..thanks for the info...i will check it again..and maybe debug the code.
FYI...i have reinstall app on 2 device and change location provider only for gps .
All the cellphone in my room.
One got stuck after 20 min and one is normal.
I will make some test for this today

**Comment by johansid** [comment]
sorry...i forgot some.
the cellphone got stuck, i turn off gps and turn on again...it back to normal
