### ISSUE TITLE
Google Earth integration

### ISSUE THREAD

**Issue by Hatchorder** [tananaev/traccar-client-android#190]
Is it possible to add a feature to allow the export of positions as Latitude and Longitude into an KML file to open in Google Earth to create a track?  This was a feature of Marinetraffic.com but they have removed it.  Or even a generic export feature to allow people to extract the data to use in other applications?

Thank you.

Ian

**Comment by tananaev** [comment]
This is a wrong repository. Issue should be here:

https://github.com/tananaev/traccar

**Comment by Hatchorder** [comment]
Sorry - moved!
