### ISSUE TITLE
Huwai P9 issue with hidden client

### ISSUE THREAD

**Issue by gitty8** [tananaev/traccar-client-android#206]
I have the issue that I loose the client after 2 hours of tracking, the process is running in background but I can't call the app to check the logs. Where I can find the else to provide it? Somewhere in file system?

Thanks

**Comment by tananaev** [comment]
The only way to open hidden app is from the dialer. I guess there is something wrong with Huawei phone app. It has custom one, right?

**Comment by gitty8** [comment]
It is not customizied by me. 
It is v3.11/app-hidden-release.apk

**Comment by tananaev** [comment]
I am talking about phone app on your device.

**Comment by gitty8** [comment]
No, it is not custom. Its default one. Phone software default EMUI 4.1 .

**Comment by tananaev** [comment]
Exactly. It's not standard Android (from Google). It's custom software from Huawei. The issue might be related to that.

**Comment by gitty8** [comment]
Ah, now I understand. So need to wait if might other people will gain same issue?

**Comment by tananaev** [comment]
Well, if you can retrieve device logs, I can investigate the issue.

**Comment by darekw** [comment]
Have you tried to add traccar to "Protected apps"? 

https://support.endomondo.com/hc/en-us/articles/220426948-How-to-solve-common-GPS-issues-on-Android

**Comment by tananaev** [comment]
@darekw, thanks for sharing the link. I think it will be useful for many people.

**Comment by roshi-mty** [comment]
Hi tananaev i just get an huawei p9 and i notice something i'm using 3.12 android 6.0

The permissions to acces phone are not enabled automatically i have to go to the app check permissions and enable phone access manually.

And one more thing if app its closed, it never get started on startup. And there is no way to open it. Only if you uninstall and then install-config.

question if the app its installed on a tablet how do you bring it back after it went into hidding?

**Comment by tananaev** [comment]
I think it's good thing that there is an extra step to open the hidden version. Extra safety.

If you force-close the app, Android won't start the app on startup. That's a security feature of Android. There is no way around it.

Most tablets have dialer app. For those that don't, unfortunately there is no solution at the moment. I'm open to suggestions. There is already a thread about this problem somewhere.

**Comment by tananaev** [comment]
I have added a URL option for opening the app. You can use link from this page:

https://www.traccar.org/client/
