### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by henrynewman** [tananaev/traccar-client-android#207]
Hi, everytime i try to compile my project I get this error, Using Android Studio

> Error:Android Source Generator: Package is not specified in AndroidManifest.xml

**Comment by tananaev** [comment]
What are you using to compile the project?

**Comment by henrynewman** [comment]
Build=Generated Signed APK
then when its about to complete it gives me the error

**Comment by tananaev** [comment]
How did you import the project?

**Comment by henrynewman** [comment]
File=New=Import Project

**Comment by tananaev** [comment]
OK, what did you select in the import wizard?

**Comment by henrynewman** [comment]
Create project from existing sources

**Comment by tananaev** [comment]
That's why you get the error. You should've selected import as gradle project.

**Comment by henrynewman** [comment]
then what do i do next?

**Comment by tananaev** [comment]
Import as gradle and build the project as before.

**Comment by henrynewman** [comment]
where should i set the gradle home?

**Comment by tananaev** [comment]
Just use the default option.

**Comment by henrynewman** [comment]
i cant it has written that the default is not configured

**Comment by tananaev** [comment]
Can I see a screenshot of what you are talking about?

**Comment by henrynewman** [comment]
![capture](https://cloud.githubusercontent.com/assets/13887235/16617747/c11078aa-4385-11e6-8d56-d6c615b4a0c9.PNG)

**Comment by tananaev** [comment]
You need to use gradle wrapper. Not sure why the options is greyed out for you. Make sure you are using latest Android Studio and do a clean checkout.

**Comment by henrynewman** [comment]
@tananaev my presentation is about to begin can i package the project then i send it to you then you compile for me.

**Comment by tananaev** [comment]
I think I found the problem. Check out latest source. I've added a missing Windows script.

**Comment by henrynewman** [comment]
@tananaev  my presentation is about to begin can i package the project then i send it to you then you compile for me.

**Comment by tananaev** [comment]
You just need an unsigned APK file? I can do it as an exception.

**Comment by henrynewman** [comment]
signed or unsigned its cool its only for a presentation.  wait a moment let me zip it

**Comment by henrynewman** [comment]
There are three projects inside
[https://www.datafilehost.com/d/9566e117](url)
get the file in the link above (no ads no nothing just the file)

**Comment by henrynewman** [comment]
@tananaev got it?

**Comment by henrynewman** [comment]
@tananaev got it?

**Comment by tananaev** [comment]
It was past 1am here when you send me the link. You can't expect me to wait for it all night.

Second thing, your link is very dodgy. It doesn't download the file. Instead it downloads some malware or something. Why are you using a file hosting like that instead of Dropbox, Google or something else?

**Comment by henrynewman** [comment]
Im sorry @tananaev  did not know it did that.
