### ISSUE TITLE
UDP protocol support

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar-client-android#215]
Hi,

I see only TCP  protocol support.

Is there any reason to not support UDP ?

Thanks.
Kiran.

**Comment by tananaev** [comment]
Traccar Client uses HTTP protocol, so it's not possible to use UDP. Why do you need UDP?

**Comment by kirantpatil** [comment]
Sir, With my limited knowledge I thought that HTTP over TCP need to
maintain session which is overhead and with UDP it just has to send the
packet without any session.

Now I understood that HTTP protocol works primarily on TCP and UDP is not
supported by HTTP.

Thanks.

**Comment by tananaev** [comment]
If by session you mean connection session, then yes. There is some overhead, but you get a guaranteed delivery unlike with UDP.

**Comment by kirantpatil** [comment]
Yes Sir, I totally agree with you.

**Comment by luke-jr** [comment]
IMO using DNS would be ideal. Then it works even behind most portals... :)

**Comment by tananaev** [comment]
@luke-jr, how is DNS related to any of the comments here?

**Comment by mwild1** [comment]
@tananaev To use DNS you could do lookups for records like `LAT.LON.DEVICEID.example.com` and then run a custom DNS server that logs the incoming DNS requests. It's a hacky way to get past various kinds of traffic filters on networks. I'm not advocating it though :)

**Comment by tananaev** [comment]
DNS uses UDP (or sometimes TCP) protocol, so I don't see any benefit.

**Comment by luke-jr** [comment]
@tananaev DNS is a UDP protocol which can be implemented such that delivery is guaranteed. The benefit is smaller data usage, and reliable transmission.

I was thinking more like:

```
	AES128( [can have max 256 bits to fit in DNS req]
		16-bit device id
		32-bit record id
		32-bit record timestamp minus 0x56000000 (Sep 21 2015 @ 13:02:56)
		32-bit lat
		32-bit lon
		24-bit alt
		24-bit speed
		24-bit bearing
		1-bit: battery state (1=charging)
		7-bit battery level
		32-bit checksum
	)
```

And supporting a reply with:

```
AES128(
	32-bit: checksum
	[16-bit: device id ONLY in checksum, not actual packet]
	32-bit: ACK report id (checksum-only when over DNS)
	8 bit: please vibrate (and ring if high bit set) now for N (lower 7 bits) timmills
	1-bit: take photo with rear camera
	1-bit: ... and upload it
	1-bit: take photo with front camera
	1-bit: ... and upload it
	1-bit: lock device
	1-bit: initiate reverse SSH
	1-bit: padding
	1-bit: response mode

	Response mode 0 (reconfigure):
		8-bit: when GPS inactive, and <interval> since last report, wake the GPS
		1-bit: when waking GPS for timeout condition (above), force making a report
		2-bit: wake GPS when network changes (0 = never; 1 = significant change; 3 = minor change)
		2-bit: wake GPS and force report when network changes (see above)
		1-bit: wake GPS and force report when battery about to die
		1-bit: except for about-to-die case, never wake GPS when battery low
		1-bit: except for about-to-die case, never send report based on time-only trigger (immediate next item)
		8-bit: when GPS is active, and <interval> since last report, make a report
		24-bit: when GPS is active, and distance is >N (high 16 bits) since last report, and <interval> (low 8 bits) since last report, make a report
		16-bit: when GPS is active, and distance is >N since last report, make a report
	Response mode 1 (missing reports; resend immediately):
		2x 32-bit: missing report ids

	If reverse SSH is enabled (only possible over UDP):
		16-bit: port number
		16-bit: len(target)
		N byte: target
)
```

Since Traccar-client-android's HTTP is super-unreliable (I need to restart the service every few weeks), I'm tempted to implement [some of?] this myself.

**Comment by tananaev** [comment]
Unreliability has nothing to do with network protocol in this case. I can't think of anything more reliable than HTTP. If there are some problem, we need to investigate why it's happening in another thread. One thing that I can tell you for sure, it's not because of HTTP protocol.

**Comment by luke-jr** [comment]
Since it works fine after the service restarts (including uploading past records immediately), I'm pretty sure it's related to using TCP in some manner or another.

**Comment by ramonsmits** [comment]
I was thinking the same. It would be nice if it could use UDP. The GPS location doesn't have to be super reliable. It is fine if an occasional location isn't received. It is perfect as it behaving like a sensor with at most once delivery behavior in most environments.

Potentially it could use a binary format to even further shrink the payload but that isn't really needed as the string easily fits within the MTU size of packet
