### ISSUE TITLE
Stops sending location after killed by task manager

### ISSUE THREAD

**Issue by juanmas07** [tananaev/traccar-client-android#224]
When you kill the application with the task manager, in some devices, the service is destroyed and stops working. I'm seeing this issue in my redmi note 2 and in huawei Y6

**Comment by tananaev** [comment]
Obviously it's not going to send any data if you kill the app. Android blocks any apps that have been explicitly killed by user.

**Comment by juanmas07** [comment]
Is there a way to make it autostart every x minutes? Me for example I kill all the running apps every time I check my phone. Also after killing, dialing he number does not bring the configuration screen so I have to reinstall in order to open it again

**Comment by tananaev** [comment]
I did some research and it seems like some manufacturers customize their task managers to kill background services. I don't think it's possible to do anything about it. I can only suggest to install an unofficial ROM that doesn't do that.

**Comment by juanmas07** [comment]
that's too bad. For example whatsapp can still receive messages, there must be a way to accomplish that. I'll investigate

**Comment by tananaev** [comment]
They use Google messaging service.

**Comment by juanmas07** [comment]
I see, that's seems for now the only way to wake up an app in this situation

**Comment by tananaev** [comment]
On standard Android there are other ways, but some manufacturers implement their "customizations" that prevent correctly written apps from functioning as designed.

Read [this page](https://support.endomondo.com/hc/en-us/articles/220426948-How-to-solve-common-GPS-issues-on-Android#manage). It has some instructions for Huawei, so it might help.

**Comment by juanmas07** [comment]
http://stackoverflow.com/questions/3856767/android-keeping-a-background-service-alive-preventing-process-death/3856940#3856940

**Comment by tananaev** [comment]
Yes, I'm using quite a few things already:

1. Foreground service
2. Alarm Manager to "wake up" the app
3. Autostart on reboot

You can also create shortcuts and then use some other app (e.g. llama app) to start the service.
