### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by avenger12345** [tananaev/traccar-client-android#23]
I was wondering how to use the traccar server. I have already created an account. I added the imeii # where it says unique identifier. How do I get the tracker to send information to the server?
Device: TK103
Thanks

**Comment by mustaphaabid** [comment]
we just got tk103 a, i can not turn the GPRS off i tried every combination but no luck so far can any one help me please

**Comment by tananaev** [comment]
@mustaphaabid, this issue tracker is for Traccar Client project only.
