### ISSUE TITLE
Android client shortcuts

### ISSUE THREAD

**Issue by samvol** [tananaev/traccar-client-android#246]
Hi,
Trying to use device automation apps like Llama, AutomateIT, Macrodroid and e.c. 
And the problem is -  shortcuts "Traccar Start" and "Traccar Stop" are **not present** in automation apps shortcuts list.
The same behavior for my LG G3 (Lollipop) and new one Xiaomi with Android 6.0.
Client's version 3.11 and 3.12.
Thank you.

**Comment by tananaev** [comment]
Have you created the links from the app?

**Comment by samvol** [comment]
Yes, of course.

**Comment by tananaev** [comment]
Then I'm not sure why they don't show up in the automation app. It might be possible to specify activity and parameters directly, without using shortcuts. Check [addShortcuts](https://github.com/tananaev/traccar-client-android/blob/master/app/src/main/java/org/traccar/client/MainActivity.java#L142) method for more info about parameters.

**Comment by samvol** [comment]
OK. I'll try. Thank you.

**Comment by imraro** [comment]
Same here. [Code](https://github.com/termux/termux-widget/tree/master/app/src/main/java/com/termux/widget) from app with expected behavior.

**Comment by tananaev** [comment]
Traccar Client already implements this functionality exactly the same way as the code that you pointed to.

**Comment by imraro** [comment]
But shortcuts from traccar is not visible from any other apps/launchers (

**Comment by tananaev** [comment]
If you can find the difference, you are welcome to point it out. As far as I can tell, they are using same API.

**Comment by imraro** [comment]
I'll try, but sadly I'm not developer.

**Comment by tananaev** [comment]
Unfortunately I don't have time to investigate it further at the moment, but with Android O release we would have to change shortcuts system anyway, so I'm review the code then.

**Comment by imraro** [comment]
Thank you!

**Comment by imraro** [comment]
I think I found it - you don't have
```
<meta-data android:name="android.app.shortcuts"
         android:resource="@xml/shortcuts" />
</activity>
```
in AndroidManifest.xml, as decribed [here](https://developer.android.com/guide/topics/ui/shortcuts.html).

**Comment by tananaev** [comment]
I appreciate the effort, but please double check the information that you share. The link points to the different type of shortcuts. You can even see it on the screenshot.

**Comment by imraro** [comment]
Sorry for the rush. New find: other apps have:
```
<intent-filter>
         <action android:name="android.intent.action.CREATE_SHORTCUT" />
</intent-filter>
```
in AndroidManifest.xml

- https://github.com/termux/termux-widget/blob/master/app/src/main/AndroidManifest.xml
- https://github.com/shadowsocks/shadowsocks-android/blob/master/mobile/src/main/AndroidManifest.xml
- https://github.com/federicoiosue/Omni-Notes/blob/develop/omniNotes/src/main/AndroidManifest.xml

**Comment by tananaev** [comment]
That's for receiving events about shortcut creation, not for creating it.

**Comment by imraro** [comment]
Creating Termux shortcut from Apex Launcher:
```
05-24 08:33:28.562 I/ActivityManager(5446): START u0 {act=android.intent.action.CREATE_SHORTCUT cmp=com.termux.widget/.TermuxCreateShortcutActivity} from uid 10196 on display 0
```
from Llama:
```
05-24 08:39:19.009 I/ActivityManager(5446): START u0 {act=android.intent.action.CREATE_SHORTCUT cmp=com.termux.widget/.TermuxCreateShortcutActivity} from uid 10158 on display 0
```

**Comment by tananaev** [comment]
I am not sure anymore what you are talking about.

**Comment by imraro** [comment]
To able to use shortcuts, other app creates them using intent action.

**Comment by tananaev** [comment]
Traccar Client also uses intent action to create shortcuts. Can you please make sure that you know what you are talking about before making any further comments.

**Comment by imraro** [comment]
I'm 99% shure:
...o you can create a shortcut to a product from there, in addition to the "Add to home screen" menu option. However if you don't want to do this simply remove the android.intent.action.CREATE_SHORTCUT intent-filter from the activity. You can still add a shortcut to the homescreen using the INSTALL_SHORTCUT permission with your existing method.

From: https://stackoverflow.com/questions/32401211/can-i-prevent-a-shortcut-android-intent-action-create-shortcut-to-appear-in-th

**Comment by tananaev** [comment]
Sorry, but you making less and less sense with every comment. How is it different what I just said? We are ALREADY USING INTENT ACTION in Traccar Client app.

**Comment by imraro** [comment]
Sorry, my English don't let me explain this right. Traccar uses INSTALL_SHORTCUT to able to install shortcuts from app itself. But you need add CREATE_SHORTCUT intent-filter to AndroidManifest.xml that other apps can create/use this shortcuts.

**Comment by tananaev** [comment]
I don't want other apps to create shortcuts.

**Comment by imraro** [comment]
Well, this should be second comment, because automation apps do this exactly (just don't adding them to Desktop).

**Comment by tananaev** [comment]
OK, I see now how it works. The app can't reuse launcher shortcuts. It needs to create own shortcuts. Is that what you are trying to say?

**Comment by imraro** [comment]
Exactly!

**Comment by tananaev** [comment]
OK, I will investigate it when I have more time.

**Comment by imraro** [comment]
Thank you!

**Comment by Larx** [comment]
Following this, too. Being able to control Traccar from Tasker would be great! Currently you can not even launch the shortcuts.

**Comment by tananaev** [comment]
I will implement this with release of new version of Android system.

**Comment by Larx** [comment]
Great!

**Comment by Larx** [comment]
Any ETA?

**Comment by tananaev** [comment]
You should ask Google when they plan to release their new version. My guess is that it's going to be somewhere in September.

**Comment by Larx** [comment]
OK, I see you couple the release of an updated app to the release of a new Android version. I didn't get that. But: Why?!

**Comment by tananaev** [comment]
Because shortcuts and notifications APIs are changing in Android O, so it doesn't make sense to implement a solution that would need to be changed in two months time again.

**Comment by Larx** [comment]
Obviously it is your own decision, but given the fact that most phones will still run Android versions < O for the next years, I consider it unfortunate to couple simple app improvements to major OS release updates. I think many Traccar users will still have a need for pre-O-compatible improvements after O is released.

**Comment by tananaev** [comment]
My point is that I don't want to do it twice.

**Comment by Larx** [comment]
Understandable, but unfortunate.

**Comment by tananaev** [comment]
Traccar Client version 5.0 has just been released. It fixes all the issues with shortcuts.
