### ISSUE TITLE
Some time connection is lost

### ISSUE THREAD

**Issue by andrejs82git** [tananaev/traccar-client-android#249]
I use traccar on my server. I use it for tracking my dog on hunting. 
On hunting we have poor signal. And some time I or dog going out from signal cover.

And when I use android app(webview) Manager Traccar some time, when I not use, a lot of time, this program on my phone and than back to this program I have old points on map. 
And helping just full restart programm. On hunting that very not good.

Thanks!

**Comment by tananaev** [comment]
So, what do you expect to see when there is no connection?

**Comment by andrejs82git** [comment]
Sorry about that issue. Looks like in newest version that problem is solved. 
(I am use docker image with oldest version)
