### ISSUE TITLE
Two tracker as one.

### ISSUE THREAD

**Issue by andrejs82git** [tananaev/traccar-client-android#250]
Hi!

I use traccar on my server for hunting with my dog.
GSM signal is not very good in area where we hunting, and I we use two tracker on one dog with different GSM provider. It normal working - some time working both device and some time working one of trackers.

But if your can add the ability to application for using two tracker as one it will be very cool! :)

**Comment by tananaev** [comment]
Not sure how this request is related to Traccar Client.
