### ISSUE TITLE
cannot open hidden app - xiaomi redmi note 3 pro

### ISSUE THREAD

**Issue by AlexanderKgr** [tananaev/traccar-client-android#251]
Installed hidden app on a xiaomi note 3 pro.
When installation finished the app open and set it up. 
Then i fix phone permissions to auto start, permission of phone and location.
The app is working and updates at my server as it should.
But when i try to open the app using dialer it closes the dialer and nothing shows.

**Comment by tananaev** [comment]
Check app permissions and make sure it has "phone" permission.

**Comment by AlexanderKgr** [comment]
all permissions are accepted and no result

**Comment by tananaev** [comment]
It must be some problem with Xiaomi phone. Possibly with their ROM or phone app.

**Comment by AlexanderKgr** [comment]
Ok thanks!
