### ISSUE TITLE
Traccar Client shortcut

### ISSUE THREAD

**Issue by Piotr70** [tananaev/traccar-client-android#253]
Hi,
"Traccar Star", "Traccar Stop" and "Traccar SOS" shortcut does not display the full name. I do not know which is which. If you can rename shortcut please. For example: "Stop Traccar"... or only "Stop"...

 Xiaomi MiMax with Android 6.0
![traccar_clinet_icon](https://cloud.githubusercontent.com/assets/25703196/22852705/7d18329a-f042-11e6-9c69-a24162c8539f.png)

**Comment by tananaev** [comment]
I am thinking we can make "Traccar" as a suffix instead of prefix.

**Comment by Piotr70** [comment]
:+1:

**Comment by tananaev** [comment]
Note that it might take a while till I find time to implement it.

**Comment by tananaev** [comment]
Prefix has been removed.
