### ISSUE TITLE
Client ID being updated needs restart

### ISSUE THREAD

**Issue by ke5stl** [tananaev/traccar-client-android#256]
hey there Anton,

I'm using the Android client, (latest), and it appears that, after updating the device identifier, that, it requires a restart of the app before the value is actually being sent (even if the change is done while the service is stopped).

best regards,
peter

**Comment by tananaev** [comment]
It shouldn't be the case, but note that device id is saved for the locally buffered data. So, if you have some unsent data in the app, it would use original device id for the old data.
