### ISSUE TITLE
Do not send position with gps off

### ISSUE THREAD

**Issue by glbatistabh** [tananaev/traccar-client-android#258]
The "Traccar Client for Android (hidden version)" application only sends the positions when the mobile device is enabled with GPS.

Even with the "location provider" set to "mixed provider", it does not use the "network provider" to get an approximate positions and does not send the positions.

Is this correct form of APP working?

** Samsung Galaxy S5 (Android 6.0)
![gs5-locationpowersave](https://cloud.githubusercontent.com/assets/8257020/24202877/ec15a85c-0ef2-11e7-8817-9c36b3e7e4b1.png)

Something similar to this:
http://stackoverflow.com/questions/6694391/android-get-current-location-of-user-without-using-gps-or-internet

**Comment by tananaev** [comment]
It means that either the network provider is disabled or there some problem with network connection.

**Comment by glbatistabh** [comment]
* **Network provider is disabled** = No. I already checked in "Traccar Client" -> "Location Provider" -> "Mixed Provider"

* **Problem with network connection** = No. When I enable GPS in "Config -> Location" start sending positions;


I think you're getting the location this way:
`LocationManager.getLastKnownLocation (LocationManager.GPS_PROVIDER)`


And in the case of the "Mixed Provider", you should test which is enabled:
```

boolean gps_enabled = false;
boolean network_enabled = false;

LocationManager lm = (LocationManager) mCtx
                .getSystemService(Context.LOCATION_SERVICE);

gps_enabled = lm.isProviderEnabled(LocationManager.GPS_PROVIDER);
network_enabled = lm.isProviderEnabled(LocationManager.NETWORK_PROVIDER);

Location net_loc = null, gps_loc = null, finalLoc = null;

if (gps_enabled)
    gps_loc = lm.getLastKnownLocation(LocationManager.GPS_PROVIDER);
if (network_enabled)
    net_loc = lm.getLastKnownLocation(LocationManager.NETWORK_PROVIDER);

if (gps_loc != null && net_loc != null) {

    //smaller the number more accurate result will
    if (gps_loc.getAccuracy() > net_loc.getAccuracy()) 
        finalLoc = net_loc;
    else
        finalLoc = gps_loc;

        // I used this just to get an idea (if both avail, its upto you which you want to take as I've taken location with more accuracy)

} else {
        // no provider is enabled
}
```

I think it's the same problem reported from this thread here:
Https://github.com/tananaev/traccar-client-android/issues/247

**Comment by tananaev** [comment]
In the thread that you are referencing, author turned OFF all location providers.

**Comment by glbatistabh** [comment]
OK!

So have no problem with the application, right?

But when I enable the GPS, it starts sending the positions. When I disabled, it stops sending even though setting _"Traccar Client -> Location Provider -> Mixed Provider -> ON"_.

**Comment by tananaev** [comment]
Try with network provider.
