### ISSUE TITLE
Very odd positioning bug from Android

### ISSUE THREAD

**Issue by jike212** [tananaev/traccar-client-android#266]
Using a Tecno W3 phone and the latest version of Traccar Client on F-Droid as well as Traccar Server. For some reason, Traccar keeps sending an old position intermittently and repeatedly causing the below track report. It uploads the correct one, then the old one, then the correct one, etc.

![traccar bug](https://cloud.githubusercontent.com/assets/28184313/25554183/7d55677c-2ccf-11e7-98e5-0f1fafefa997.PNG)

**Comment by tananaev** [comment]
You should probably check server logs to see what device sent for the selected period.

**Comment by jike212** [comment]
Is the `tracker-server.log` kept in UTC or the time zone set in the web ui? I'm not finding any entries for the times the records were sent in the logs for that specific device ID.

**Comment by tananaev** [comment]
Log is obviously using server timezone.

**Comment by jike212** [comment]
The server logs reflect the exact same positions as what's listed in the report that was exported. The exported reports also reflect significant variances in battery level (up and down multiple times even though the phone is unplugged for the full duration of time) indicating the possibility that previous location fixes are not being submitted in order.

**Comment by tananaev** [comment]
So, where is the invalid data is coming from? It must be in the server log.

**Comment by jike212** [comment]
It's coming from the phone. Is there an email address I can send the server log capture from as well as the report from Traccar Server?

I can send you the raw server log info via email as well as the report from Traccar Server that shows the battery level fluctuations which is easier to spot than the raw coordinates themselves.

**Comment by tananaev** [comment]
Email address is in profile.

**Comment by tananaev** [comment]
It seems like you are using a proxy. The problem is that proxy re-uses same connection for different devices, so devices are all mixed up. Next time you should probably mention that you have a proxy in front of Traccar, or any other relevant information.

**Comment by jike212** [comment]
The phones use a proxy on the APN to whitelist websites and prevent excessive data usage as it becomes extremely costly. I would assume that many businesses do something similar to control usage costs.

Also, doesn't the phone send the identifier in the request anyways? How could the devices get mixed up if it sends the ID in the request itself?

**Comment by tananaev** [comment]
Because ids are cached per connection to improve performance. You can use `decoder.ignoreSessionCache` parameter to disable it.

My point is not that you can't use proxy. You can, but knowing that you are using proxy would help to avoid wasting time on searching for the problem.

**Comment by jike212** [comment]
Perhaps this is worth adding to the troubleshooting page on the Traccar website then? https://www.traccar.org/troubleshooting/

Rather than users causing you to be upset or angry because they are experiencing issues, it might be better to update that page with questions like mine so that future users don't open up similar issues.

It is not a well-known fact that using a proxy matters with Traccar as most users would assume that the device ID being different in each request would signal Traccar Server to log the event with that specific device ID, not a different one. The caching is more likely to undermine the need for having an ID in the first place.

**Comment by tananaev** [comment]
Unfortunately it's not possible to mention every small thing like this. It's just one of 140 supported protocols and this issue doesn't actually apply to most of the other protocols.
