### ISSUE TITLE
Possible Bug? - Frequency value = 0 not able to set

### ISSUE THREAD

**Issue by jaimzj** [tananaev/traccar-client-android#267]
Hello Anton,

I have tried the new version of android client for android, Fresh install.

As per the release blog post, You have mentioned Frequency can be set to 0 if any of the other 2 values are set that is angle or distance, hence I have set distance to 300 and frequency I am trying to set to 0 however it just does not save as 0. it remains the same value that has been set previously, I can even set it as 1 but not 0.

Please advice, Am I doing something wrong or is this a bug?

**Comment by tananaev** [comment]
It was a mistake in the blog post. I've updated it. You can't completely disable time frequency, but you can set it to some high number (e.g. 100000) effectively disabling it.

**Comment by jaimzj** [comment]
Oh that's great 👍  will set it to high number like you suggested and try,
