### ISSUE TITLE
Location update isn't working

### ISSUE THREAD

**Issue by dave22786** [tananaev/traccar-client-android#270]
The traccar client hidden or normal for Android stop sending position after a while, i had to open the app again and restart the service and if i'm lucky works again, if not i had to do the same a couple of times, and works fine for a couple of minutes and stops again.

**Comment by tananaev** [comment]
You have to add Traccar Client for battery optimization exceptions.

**Comment by dave22786** [comment]
Thanks for your reply, where I can find that option in Android 4.4.2

**Comment by tananaev** [comment]
There is no such option in official version of Android 4.4, as far as I know, but there might be some vendor specific configuration.

**Comment by dave22786** [comment]
Did you mean a third party app?

**Comment by tananaev** [comment]
No, I meant phone manufacturer software.

**Comment by dave22786** [comment]
Thank you very much, I found one and I will try, if everything's ok I will close the issue, if not I'll write you again.
