### ISSUE TITLE
dont't work on honor 5c in background

### ISSUE THREAD

**Issue by vitalyermolovich** [tananaev/traccar-client-android#274]
App doen't work on honor 5c in background when the screen is off.
http://storage4.static.itmages.com/i/17/0530/h_1496135867_8830511_17a6dc640a.png

My phone
http://storage8.static.itmages.com/i/17/0530/h_1496135584_6745510_d259cb4117.png

My setiings
http://storage9.static.itmages.com/i/17/0530/h_1496135312_7136628_41a2b12b31.png
http://storage5.static.itmages.com/i/17/0530/h_1496135386_8522117_eee66a9c9d.png
http://storage2.static.itmages.com/i/17/0530/h_1496135488_8023076_bb1c0f3cbc.png

**Comment by tananaev** [comment]
Looks like everything is configured properly. Not sure what else can be done.

I am planning to create another app that would use push notifications to wake up and report location. That might be the only solution that would work on your phone.

**Comment by vitalyermolovich** [comment]
I understand that it's the firmware?

**Comment by tananaev** [comment]
I think so. If that's an option you can try to find a AOSP-based ROM for your device and try it. App works fine on official version of Android.

**Comment by vitalyermolovich** [comment]
This firmware even Navitel kills

**Comment by vitalyermolovich** [comment]
thanks a lot
