### ISSUE TITLE
[Feature request] on-the-fly configuration change 

### ISSUE THREAD

**Issue by oliv3** [tananaev/traccar-client-android#276]
Hi, first thanks for traccar 
Being able to change the configuration without stopping and restarting would be a neat feature 
Especially when debuging ie changing hosts

**Comment by oliv3** [comment]
s/ie/eg

**Comment by tananaev** [comment]
Actually older versions used to support it, but it makes logic more complicated and there is very little value in this feature. In most cases people set everything up and forget about it.
