### ISSUE TITLE
Mysql Database creation.

### ISSUE THREAD

**Issue by akmal1999** [tananaev/traccar-client-android#277]
Hi,

I created a new instance of traccar locally however, when I run traccar it does not create all the tables.

it only creates the tables in the attached document.

attached please find server and wrapper files too.
![dberror](https://user-images.githubusercontent.com/22064319/27375037-e24f1a2a-563b-11e7-9e8c-abe81b673488.PNG)

[wrapper.log.20170621.zip](https://github.com/tananaev/traccar-client-android/files/1090888/wrapper.log.20170621.zip)

**Comment by tananaev** [comment]
I suspect that your configuration is incorrect. Please check this page:

https://www.traccar.org/mysql/

**Comment by akmal1999** [comment]
Hi,

I copied and pasted the same configuration from your script and only amended the user credentials and database.

Any other opinion while I will revisit this again.

Many thanks.

**Comment by tananaev** [comment]
Can I see config?

**Comment by akmal1999** [comment]
Attached please find the file.
[traccar.txt](https://github.com/tananaev/traccar-client-android/files/1093451/traccar.txt)

**Comment by tananaev** [comment]
That's not a valid config file. Anyway, the URL string looks OK, so I guess the problem is with something else. Possibly MySQL version is very old.

**Comment by akmal1999** [comment]
Hi Anton,

When you say it is not a valid config file what do you mean? This is the original file that gets installed.
attached please find the mysql version.
![msyql version](https://user-images.githubusercontent.com/22064319/27415008-a7334fc8-56d2-11e7-9bce-0c3c12f7b0de.PNG)

**Comment by akmal1999** [comment]
I uninstalled mysql because it was creating these many tables and reinstalled it and still it creates these many tables as mentioned in previous emails.

**Comment by tananaev** [comment]
You haven't copied you config file properly, that's why it's invalid. I guess it valid on the actual server.

If you provide access to the server, I can try to check why it's happening.

**Comment by akmal1999** [comment]
this is an internal server and you can not connect from outside it is in my home... however teamviewer can work if you would like to connect.

**Comment by tananaev** [comment]
TeamViewer is too slow. I need SSH access.
