### ISSUE TITLE
Different version on Github compared to PlayStore

### ISSUE THREAD

**Issue by Criccle** [tananaev/traccar-client-android#278]
I have been playing around with Traccar from the Android PlayStore and wanted to know more about it, so I downloaded the latest version from Githbub. What I find strange is that, even though the version number is the same, the input options for the client differ very much. The Github version, for example, doesn't show a seperate Port input. I would like to verify which one of these is the latest and check if the Github version isn't actually outdated.

**Comment by tananaev** [comment]
GitHub is ahead of released version. It has latest modifications that haven't been released yet. But you can always get specific version from GitHub releases:

https://github.com/tananaev/traccar-client-android/releases

**Comment by Criccle** [comment]
Thanks! That's exactly what I wanted to know. :)
