### ISSUE TITLE
Use POST requests

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar-client-android#279]

**Comment by JosefRypacek** [comment]
You are using POST, but data are passed as GET parameters. I've modified my fork to use real POST request. This can be useful when sending a lot of data. Gzip compression is also working only for content.

https://github.com/JosefRypacek/traccar-client-android/commit/3003dda6c59465773bd9255715e53bdd0c2c6290

## Before
`POST /?id=123&timestamp=456&lat=1&lon=2&speed=0.0&bearing=0.0&altitude=0.0&accuracy=30.0&batt=30.0 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
User-Agent: xxx
Host: xxx
Connection: Keep-Alive
Accept-Encoding: gzip
Content-Length: 0`

## After
POST / HTTP/1.1
Content-Type: application/x-www-form-urlencoded
User-Agent: xxx
Host: xxx
Connection: Keep-Alive
Accept-Encoding: gzip
Content-Length: 135
id=123&timestamp=456&lat=1&lon=2&speed=0.0&bearing=0.0&altitude=0.0&accuracy=30.0&batt=30.0`

**Comment by tananaev** [comment]
The format is there for historical reasons. There are many servers that support old Traccar Client format. Also, it doesn't really bring much benefit because payload will be small anyway. If we had some kind of batching it would make more sense.
