### ISSUE TITLE
Удалённая настройка клиента на андроид

### ISSUE THREAD

**Issue by uzazzap** [tananaev/traccar-client-android#281]
Привет! Прошу прощения если я плохо искал, но я не нашёл ответ на свой вопрос: Есть ли возможность каким либо образом настраивать клиент удалённо (смс, файл в корне карты памяти и т.п.). Ранее использовался GPSLogger by Mendhak, но в нём нет возможность отправлять данные которые были собраны в отсутствие интернета.

**Comment by tananaev** [comment]
К сожалению такой возможности нету на данный момент.

**Comment by uzazzap** [comment]
А в планах добавление этого функционала нет?

**Comment by tananaev** [comment]
Пока что нету.
