### ISSUE TITLE
Suggestion for Android and IOS clients

### ISSUE THREAD

**Issue by kennethdd2** [tananaev/traccar-client-android#295]
The Earlier versions had the option to install shortcuts as an sos button, start, stop.  Suggest a user or admin configureable shortcut that allows custom icon label and associated custom event code/name.  This would be an application that would allow numerous shortcuts and events.  As an example if the client wanted to use this to supplement the normal use of the system to have employees time clock, clock in/clock out, arrived at work site, left site, at lunch etc.  
Preferable this could actually be version independent, just would use the current code/api.
Your thoughts?
  

-->

**Comment by tananaev** [comment]
Shortcuts are still there. You can add them standard way from your android launcher.

**Comment by kennethdd2** [comment]
I understand thank you.  I will look at them in more detail and let you know my thoughts to expand upon their use. FYI the USPS uses a system similar to yours with a number of refinements that allow not just vehicle monitoring but detailed carrier(postman) data to be monitored and managed in for quality of service big data analysis.
