### ISSUE TITLE
Clicking on service notification should go to app activity

### ISSUE THREAD

**Issue by garyvdm** [tananaev/traccar-client-android#299]
**Steps to reproduce:**

- Start service
- Open notification bar
![screenshot_20171212-073721](https://user-images.githubusercontent.com/352175/33869052-720fe5ca-df0f-11e7-9e2e-6e1c7e29c86b.png)
- Click on service notification

**Actual Result:**

- Android app settings page is opened, with option to Stop app, or uninstall
![](https://user-images.githubusercontent.com/352175/33869063-843c864a-df0f-11e7-94d6-62491acd58da.png)

**Desired Result:**

- App activity should be opened, so that one can easily stop service, view status logs, or change settings.
![screenshot_20171212-073731](https://user-images.githubusercontent.com/352175/33869068-8b43f040-df0f-11e7-90a6-1c68132aff46.png)

**Comment by tananaev** [comment]
That's not our app notification. It's an Android system notification indicating that the app is running in the background. We have no control over that notification from the app side.
