### ISSUE TITLE
Wrong location sent from time to time

### ISSUE THREAD

**Issue by Phyks** [tananaev/traccar-client-android#309]
Hi,

It seems for some reason that traccar fails to get my current location from time to time. Then, it sends a latitude and longitude of both 0 (I guess this is from a safe default value from the code), which is a complete non-sense.

I'm not very familiar with Android app, but it sounds like it gets the 0, 0 point from default values at some point, and simply send them. I would have expected it to simply discard the point if it cannot acquire position.

Thanks!

**Comment by tananaev** [comment]
Traccar Client app never sends zeroes by itself. It always reports location returned by Android APIs.

**Comment by Phyks** [comment]
Hmm, I gave a try at [uLogger](https://github.com/bfabiszewski/ulogger-android/) to compare, and check whether I had similar weird locations.

It turns out that, contrary to Traccar, uLogger [crashes periodically](https://github.com/bfabiszewski/ulogger-android/issues/29#issuecomment-354677982). This is what made me think that when there is a problem to fetch location, uLogger would have a missing test and crash and Traccar would handle it as zero. But I might be wrong on this…

**Comment by tananaev** [comment]
There are no tests for zero or invalid location. Traccar Client reports what it gets directly from Android system, which in turns gets it from GPS (in case of GPS location provider).
