### ISSUE TITLE
I want traccar-client-android expert's help

### ISSUE THREAD

**Issue by xiaohan20** [tananaev/traccar-client-android#312]
I'd like to build my own GPS app using traccar-client-android.
Users will login app using <id, password>
After login success, user will get device id from server automatically.
All functions will be same as traccar-client-android's original app feature.
Web API for Login is already finished.
If you can do it, feel free to contact me.
My email : saeedmohamed451@yahoo.com
Thank you

**Comment by tananaev** [comment]
We provide customisation services. Please send an email to discuss it. Address is in the profile.
