### ISSUE TITLE
Wrong location sent from time to time

### ISSUE THREAD

**Issue by denon2002** [tananaev/traccar-client-android#322]
Hello,

i have a problem.

Since update the android APP from 5.7 to 5.8 send my OnePlus 2 with Android 7.1 regularly a wrong position.
It is always the following position: 
latitude: 51.59000015258789
longitude 10.390000343322752

I have the same problem with a another OnePlus.

Have you a idea ?

**Comment by garyvdm** [comment]
What is your accuracy setting set to? If it is on medium, try setting it to high.

**Comment by denon2002** [comment]
Hy,

thanks for the fast answer.
yes, i have in the settings "medium". I will try "high"

**Comment by denon2002** [comment]
Hy, after 1 hour, i think this works. Thanks.... i will take "high" in the settings.
