### ISSUE TITLE
Connection failed on android

### ISSUE THREAD

**Issue by piojankow** [tananaev/traccar-client-android#51]
Hi All, I'm new on GitHub.

I'd like to use traccar for tracking my smartphone SonyXperia Sola MT27i (with android 2.3.7) on Synology DS213 with DSM 4.2-3211. I have also router Buffalo WZR-HP-G300NH2 with firmware: DD-WRT v24SP2-MULTI  

I'v been trying to connect android with synology for last few days but still doesn't work - connection failed on android. That's why I'd like to ask for support.
I suspect I have a problem with correct port forwarding on my router.
I will describe step by step my settings:
1. I have installed traccar on my synology (during installation I've selected to open all ports) and forwarded ports on buffalo:

For externall access (from work) I use public IP and port 443 which is forwarded by router to local synology address 192.168.11.2 and port 7777:

http://my_public_IP:443  ->forwarder by router-> 192.168.11.2:7777

In this way I can open program at work.

I have forwarder also external port 55005 also to 192.168.11.2:7777

http://my_public_IP:55005  ->forwarder by router-> 192.168.11.2:7777
1. My android settings are:
   Server address: http://my_public_IP   (without port, only IP number)
   Server port: 443
   Location provider: mixed

I have still status:
Location updated
Connection failed

I have attached picture as well.
![buffalo settings](https://f.cloud.github.com/assets/5240439/973677/a8afef94-0638-11e3-8aa9-e71b489cd68e.jpg)

Thanks in advance for support.
Piotr

**Comment by 2SI3NX** [comment]
Hi, @tananaev  Please can you clear this up below?
I have configured nginx with https proxying so the server web interface works with https from outside.

Currently in the android traccar client it has an option of Encryption Enabled,
If i enable this and put port 443 in the client, and i open port 443 in router, it never shows any error in status updates but at the same time does NOT update the server with gps location.

If i open port 5055 as well in router and put that port in the client and disable encryption then i get updates and it works.

1. Can you please clarify what the encryption enabled option is in the client? And when can it be used?
2. Is it not possible to just use ONE port, the https 443 port in the client ??
3. Why open 2 ports, one for web interface and one for android client? - is that mandatory to have both web interface AND android client working?

Please help clarify this issue.

**Comment by tananaev** [comment]
@2SI3NX, it sounds like you proxied web interface port, but not OsmAnd port.

**Comment by 2SI3NX** [comment]
@tananaev, ok but how do you proxy OsmAnd port?  Any tutorial in the documentation on how to do that?
And after that will I be able to only need to open 443 to work for both client and web interface?

**Comment by tananaev** [comment]
It sounds like you don't fully understand how HTTP and proxying works. I would suggest to research it first.

As for configuring proxy, I don't have any tutorial, but I'm sure there is plenty of information on this topic online.

**Comment by 2SI3NX** [comment]
It would be really nice if you could **help** by directing me to the correct link to proxy your **OsmAnd port to be used as 443**, as well as answering the questions in my first post about what the option of 'Encryption Enabled' does exactly in the client if you already can use port 443 as the server port in the client.

Id like to use your software by using the features you provide, such as securing a traccar server and using port 443 for OsmAnd port.  Im sure im not the only one that needs to know about securing a traccar server fully.
Your help would be appreciated

**Comment by tananaev** [comment]
Port for web interface and port for OsmAnd protocol (Traccar Client) are two completely different things. I don't understand how you want them to work on the same port.

**Comment by 2SI3NX** [comment]
@tananaev  What i wanted was to use https (443) ONE SECURE CONNECTION PORT for both the Android app AND the web interface.
Trying to understand your application, it seems when i used nginx to proxy both those to port 443, i could not specify a location block to proxy specific port 8020 for web interface and 5055 for android app at the same time. such as: `location /traccar/web {` and `location /traccar/app {`  for example.

I asked the nginx professionals, and they said that a way around this is to use 2 dyndns domains that point to the same ip address to 2 different Server {} blocks.

I have configured this to proxy both ports 8020 and 5055 to 443 secure port. with the following config in nginx example.com  as below:

server {
        listen 443;
        server_name dyndns8082.example.com;

        root html;
        index index.html index.htm;

        ssl on;
        ssl_certificate /opt/traccar_cert/server8082.crt;
        ssl_certificate_key /opt/traccar_cert/server8082.key;
        ssl_session_timeout 5m;
        ssl_prefer_server_ciphers on;

        location / {
          proxy_redirect off;
          proxy_buffering off;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          port_in_redirect off;
          proxy_connect_timeout 900;
          proxy_send_timeout 900;
          proxy_read_timeout 900;
          send_timeout 900;
                proxy_pass http://127.0.0.1:8082;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        }
}

server {
        listen 443;
        server_name dyndns5055.example.com;

        root html;
        index index.html index.htm;

        ssl on;
        ssl_certificate /opt/traccar_cert/server5055.crt;
        ssl_certificate_key /opt/traccar_cert/server5055.key;
        ssl_session_timeout 5m;
        ssl_prefer_server_ciphers on;

        location / {
          proxy_redirect off;
          proxy_buffering off;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          port_in_redirect off;
          proxy_connect_timeout 900;
          proxy_send_timeout 900;
          proxy_read_timeout 900;
          send_timeout 900;
                proxy_pass http://127.0.0.1:5055;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        }
}

As far as i know this helps secure both communications between android traccar client AND web interface at the same time.

This is what was needed. However, it would be better to proxy in different location blocks, in other words, being able to specify through nginx to which location the traccar client app is sitting so that it can proxy_pass the correct port, instead of creating multiple dyndns domains for this purpose.

Hope you understand now. and hope this helps someone else.

This way also eliminates opening 2 unnecessary and unsafe ports in the router and only requires opening port 443 for secure communication.

Can you answer my question about what exactly the 'Encryption Enabled' option in the traccar client does?  What is the code behind it?

**Comment by tananaev** [comment]
Now this makes much more sense. You can use virtual hosts like that, but note that not all versions of Android support it. More recent ones do.

Traccar Client always uses root path to send data. You can put the web interface in a different "location block" if you want.

**Comment by 2SI3NX** [comment]
@tananaev Can you answer my question about what exactly the 'Encryption Enabled' option in the traccar client does? What is the code behind it?

**Comment by tananaev** [comment]
It changes protocol from HTTP to HTTPS. That's it.
