### ISSUE TITLE
GPS location still occurs with service set to 'off'

### ISSUE THREAD

**Issue by nbonniere** [tananaev/traccar-client-android#66]
The GPS icon (indicating a fix is being acquired) shows up at the same rate (as per the 'frequency' set in the settings) in the status bar whether the service is 'stopped' or 'running', after installation.
When you want to stop the real-time tracking and set the service to 'off' I would have expected the GPS location to stop as well. I have to go to the application manager and stop the service for the GPS to stop turning on and use power.
Samsung Ace 2 x (GT-S7560M) (Android 4.0.4)

**Comment by tananaev** [comment]
Closing as stale. Create a new issue if there are still some issues.
