### ISSUE TITLE
Add documentation describing the message formats

### ISSUE THREAD

**Issue by tacman** [tananaev/traccar-client-android#67]
Can you add documentation describing the extended format and the standard format?

For extended, even just adding a link to 

http://aprs.gids.nl/nmea/#rmc  

would help.  Obviously, programmer can look at the source at https://github.com/tananaev/traccar-client-android/blob/master/traccar-client/src/main/java/org/traccar/client/Protocol.java, but a quick explanation of each field would be much easier.

**Comment by tananaev** [comment]
Documentation for old format:

https://www.traccar.org/traccar-client-protocol/

Documentation for new format:

https://www.traccar.org/osmand/
