### ISSUE TITLE
I can't see my device in demo.traccar.org/

### ISSUE THREAD

**Issue by dngiraldoc** [tananaev/traccar-client-android#80]
Hello, 

Could you  please tell me if I made a mistake with my Traccar client?.

I installed Traccar client in my Galaxy note II mobile phone, I registered the IMEI, as  shown in 'Device identifier' sectoin of the app at http://demo.traccar.org/ , and  I also tried with IMEI as shown with *#06# code, wich has '/ 01' following the IMEI. I tried to locate my phone in http://demo.traccar.org/, but I  have been able to do it, It tried with intervals of 1, 15 and 60 seconds, selecting the 3 options in location provider (GPS provider, net provider and mixed) but, anyway, I can't locate my phone at http://demo.traccar.org/, it always the message "No results found for selected period" is shown.

Could you please help me?

Best regards,

David Giraldo

**Comment by tananaev** [comment]
Closing as stale. Create new issue if there are still some problems.
