### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Ferretdog** [tananaev/traccar-client-android#83]

**Comment by Ferretdog** [comment]
Done. I actually built this myself. If anyone wants a copy, please contact me. traccar at getlost.com.au

**Comment by lucianotj** [comment]
Hi, i need a copy too!!! pls contact me lucianotj at gmail . com 
will gladly pay for that!

**Comment by Tucsondirect** [comment]
all you have to do is change the app name and icon, and change some menu
visibility items...

**Comment by lucianotj** [comment]
I am so sorry, but I am not a developer... i dont know how to do this changes. I aprecciate any help.

**Comment by Ferretdog** [comment]
I built it from scratch using (I'm not a dev) Tasker with its App Factory. When first installed it throws up some setup screens to let you set the interval, the server and port, then it goes silent. Running it from the icon after that does nothing visible. The app constructs an gets a URL using the mask:

http://host:5055/?id=test&lat=-34.0001&lon=144.001&timestamp=1424231173&hdop=[insert_battery_percentage]&altitude=1&speed=10

That's pretty much it. It doesn't do much, so it didn't take long. I'm not a developer so I wasn't the one to actually fork this app and change it.

**Comment by muhamedoufi** [comment]
> Done. I actually built this myself. If anyone wants a copy, please contact me. traccar at getlost.com.au
> 
> I won't go into how it's hidden here, but it includes a configurable server and port, configurable base interval, accelerated interval when moving, and a bunch of additional triggers (phone ringing, message received, etc). It runs silently on boot, and it hides in plain sight.

how are you i want to implement also this feature in traccar client , but until now , i don't know how to implement it , i ask some questions on traccar forum and on stackoverflow , but i don't find response , give me your contact , if you implement this , Thank you

**Comment by tananaev** [comment]
No personal contact sharing please.
