### ISSUE TITLE
I cannot see my device in demo map

### ISSUE THREAD

**Issue by adminlican** [tananaev/traccar-client-android#86]
it always shows "No results found for selected period"

I deploy it According to the following guide 

"By default application configured to use free Traccar service (address - demo.traccar.org, port - 5005). To see you device on map visit demo.traccar.org and add your device IMEI number via web interface."

**Comment by vamsi4321** [comment]
Hi,
it always shows "No results found for selected period"
this ismy device id 
866225029956196

**Comment by tananaev** [comment]
@vamsi4321, this is a 2 years old thread. Please create a new one with all the details (what server, port, time etc).
